# Generated by Django 5.1.6 on 2026-01-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="task",
            table="tasks",
        ),
        migrations.AlterModelTable(
            name="taskdependency",
            table="task_dependency",
        ),
    ]
