# Generated by Django 5.1.6 on 2026-01-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_table_alter_taskdependency_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="task",
            table=None,
        ),
        migrations.AlterModelTable(
            name="taskdependency",
            table=None,
        ),
    ]
